import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomeTemplate from '../components/templates/home/HomeTemplate'
import { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Family Fun Board</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
      <HomeTemplate />
      </main>
    </>
  )
}

export default Home