import Head from 'next/head'
import HomeTemplate from '../components/templates/home/HomeTemplate'
import { NextPage } from 'next'
import CommonLayout from '../components/layouts/commonLayout/commonLayout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Family Fun Board</title>
        <meta name='description' content='Generated by create next app' />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <CommonLayout>
        <HomeTemplate />
      </CommonLayout>
    </>
  )
}

export default Home
